version: "3"

services:

  mongo:

    image: mongo:5.0.6
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: gfhjkm

    volumes:
      - /db/mongo/data:/data/db

    ports:
      - "27017:27017"

    networks:
      - dbserver

networks:
  dbserver:
    driver: bridge
